version: "3.9"
services:
  api:
    build: .
    container_name: agendamento_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
